// <auto-generated />
namespace DataService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta1-30916")]
    public sealed partial class kk1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kk1));
        
        string IMigrationMetadata.Id
        {
            get { return "201410102216509_kk1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
