// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DataService.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta1-30916")]
    public sealed partial class kk1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kk1));
        
        string IMigrationMetadata.Id
        {
            get { return "201411131928503_kk1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
