// <auto-generated />
namespace DataService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class kk2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kk2));
        
        string IMigrationMetadata.Id
        {
            get { return "201412170357188_kk2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
