// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DataService.Migrations.SchoolContext
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v));
        
        string IMigrationMetadata.Id
        {
            get { return "201504041340516_v "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
