//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace DataService.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("DataService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Classes] ([ClasseGuid], [Name], [Sigle], [Session], [MaxEffectif], [FiliereGuid], [ClassGrade], [Description], [InscriptionAmount], [MonthlyAmount], [QuarterlyAmount], [HalfYearlyAmount], [YearlyAmount], [AddUserGuid], [DateAdded], [LastEditDate], [LastEditUserGuid], [IsDeleted], [DeleteUserGuid], [DeleteDate]) VALUES (N&apos;9c273148-f407-4a08-b536-071b036590c6&apos;, N&apos;2 eme Année&apos;, N&apos;2 eme Année&apos;, N&apos;Printemps&apos;, 35, N&apos;ce7f5c63-a279-434d-aa5e-4edd3a69e10f&apos;, 2, N&apos;2 eme Année&apos;, 800, 1200, 1200, 900, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_Classes_data {
            get {
                return ResourceManager.GetString("dbo_Classes_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Filieres] ([FiliereGuid], [Name], [Sigle], [TypeFormation], [Cycle], [Diplome], [Departement], [Admission], [Scolarite], [Description], [AddUserGuid], [DateAdded], [LastEditDate], [LastEditUserGuid], [IsDeleted], [DeleteUserGuid], [DeleteDate]) VALUES (N&apos;5ba5aa7a-e631-4af1-ba2d-2f69485dd69f&apos;, N&apos;Genie Civil&apos;, N&apos;TGC&apos;, NULL, NULL, N&apos;Ingénieur&apos;, N&apos;Genie Civil&apos;, N&apos;Bac&apos;, 3, NULL, N&apos;00000000-0000-0000-0000-000000000000&apos;, N&apos;2015-03-31 01:34:18&apos;, N&apos;2015-03-31 01:34:18&apos;, N&apos;00000000-0000-0000-0000-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_Filieres_data {
            get {
                return ResourceManager.GetString("dbo_Filieres_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[People] ([PersonGuid], [Title], [FirstName], [LastName], [HealthState], [Nationality], [IdentityNumber], [BirthDate], [BirthPlace], [PhoneNumber], [EmailAdress], [HomeAdress], [RegistrationDate], [AddUserGuid], [DateAdded], [LastEditDate], [LastEditUserGuid], [IsDeleted], [DeleteUserGuid], [DeleteDate]) VALUES (N&apos;a1bc1aa1-1efc-42ff-bc12-004726372948&apos;, 0, N&apos;Samira&apos;, N&apos;Khalis&apos;, 0, N&apos;Maroc&apos;, N&apos;PO-124547&apos;, N&apos;1995-03-30 00:00:00&apos;, N&apos;Rabat&apos;, N&apos;+212 624-965872&apos;, N&apos;Samira@gmail.com&apos;, NULL, NULL,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_People_data {
            get {
                return ResourceManager.GetString("dbo_People_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Staffs] ([StaffGuid], [PersonGuid], [Matricule], [PositionPrincipale], [DepartementPrincipale], [Division], [Qualification], [Diploma], [DiplomaLevel], [Experiences], [FormerJob], [Grade], [HiredDate], [Statut]) VALUES (N&apos;39690a52-3685-4c78-bf7a-0e1588323f71&apos;, N&apos;6d26fe5c-c26f-450e-8481-ec46bb112042&apos;, N&apos;SZ-315-8783&apos;, NULL, N&apos;Departement Genie Civil&apos;, NULL, N&apos;Doctorat En Mathematique&apos;, NULL, NULL, 21, NULL, N&apos;Junior&apos;, NULL, 0)
        ///INSERT INTO [dbo].[Staffs] ([StaffGuid], [PersonGuid], [Matricu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_Staffs_data {
            get {
                return ResourceManager.GetString("dbo_Staffs_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Subjects] ([SubjectGuid], [Name], [Sigle], [Discipline], [TypeMatiere], [Module], [StudyLanguage], [WeeklyHours], [TempsPrescrit], [HourlyPay], [Coefficient], [Couleur], [Description], [AddUserGuid], [DateAdded], [LastEditDate], [LastEditUserGuid], [IsDeleted], [DeleteUserGuid], [DeleteDate]) VALUES (N&apos;63705009-21d7-4f7e-bd3a-00af5eacf212&apos;, N&apos;Marketing&apos;, N&apos;MAR-785&apos;, NULL, NULL, N&apos;Module A&apos;, N&apos;Français&apos;, N&apos;18:00:00&apos;, N&apos;00:00:00&apos;, 1200, 8, N&apos;#FFFFB6C1&apos;, N&apos;Marketing&apos;, N&apos;9e9a7a74-6d63-4bb3-be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_Subjects_data {
            get {
                return ResourceManager.GetString("dbo_Subjects_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap defaultStaff {
            get {
                object obj = ResourceManager.GetObject("defaultStaff", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap defaultStudent {
            get {
                object obj = ResourceManager.GetObject("defaultStudent", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap No {
            get {
                object obj = ResourceManager.GetObject("No", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[People] ([PersonGuid], [Title], [FirstName], [LastName],  [HealthState], [Nationality], [IdentityNumber], [BirthDate], [BirthPlace], [PhoneNumber], [EmailAdress], [HomeAdress], [RegistrationDate], [AddUserGuid], [DateAdded], [LastEditDate], [LastEditUserGuid], [IsDeleted], [DeleteUserGuid], [DeleteDate]) VALUES (N&apos;a1bc1aa1-1efc-42ff-bc12-004726372948&apos;, 0, N&apos;Samira&apos;, N&apos;Khalis&apos;,  0, N&apos;Maroc&apos;, N&apos;PO-124547&apos;, N&apos;1995-03-30 00:00:00&apos;, N&apos;Rabat&apos;, N&apos;+212 624-965872&apos;, N&apos;Samira@gmail.com&apos;, NULL, NULL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string People_Students {
            get {
                return ResourceManager.GetString("People_Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait1 {
            get {
                object obj = ResourceManager.GetObject("portrait1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait10 {
            get {
                object obj = ResourceManager.GetObject("portrait10", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait11 {
            get {
                object obj = ResourceManager.GetObject("portrait11", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait12 {
            get {
                object obj = ResourceManager.GetObject("portrait12", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait13 {
            get {
                object obj = ResourceManager.GetObject("portrait13", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait14 {
            get {
                object obj = ResourceManager.GetObject("portrait14", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait15 {
            get {
                object obj = ResourceManager.GetObject("portrait15", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait16 {
            get {
                object obj = ResourceManager.GetObject("portrait16", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait17 {
            get {
                object obj = ResourceManager.GetObject("portrait17", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait18 {
            get {
                object obj = ResourceManager.GetObject("portrait18", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait19 {
            get {
                object obj = ResourceManager.GetObject("portrait19", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait2 {
            get {
                object obj = ResourceManager.GetObject("portrait2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait20 {
            get {
                object obj = ResourceManager.GetObject("portrait20", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait21 {
            get {
                object obj = ResourceManager.GetObject("portrait21", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait22 {
            get {
                object obj = ResourceManager.GetObject("portrait22", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait3 {
            get {
                object obj = ResourceManager.GetObject("portrait3", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait4 {
            get {
                object obj = ResourceManager.GetObject("portrait4", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait5 {
            get {
                object obj = ResourceManager.GetObject("portrait5", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait6 {
            get {
                object obj = ResourceManager.GetObject("portrait6", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait7 {
            get {
                object obj = ResourceManager.GetObject("portrait7", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait8 {
            get {
                object obj = ResourceManager.GetObject("portrait8", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait9 {
            get {
                object obj = ResourceManager.GetObject("portrait9", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Staffs (StaffGuid, Matricule, PositionPrincipale, DepartementPrincipale, Qualification, HiredDate, Statut, Title, FirstName, LastName, Nationality, IdentityNumber, BirthDate, BirthPlace, PhoneNumber, EmailAdress, HomeAdress, RegistrationDate) values (&apos;2f4d931a-3f40-48f6-8ab9-8d48f0cc0966&apos;, &apos;XV-530-1856&apos;, &apos;Directeur&apos;, &apos;Departement des Finances&apos;, &apos;Master En Finance&apos;, &apos;2013-09-17 10:04:13&apos;, &apos;0&apos;, &apos;0&apos;, &apos;Sandra&apos;, &apos;Hughes&apos;, &apos;Indonesia&apos;, &apos;3579086869548721&apos;, &apos;10/2/2014&apos;, &apos;Cibatu&apos;, &apos;2-(762)299-0601&apos;, &apos;shu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Staffs {
            get {
                return ResourceManager.GetString("Staffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Students (StudentGuid, StudentId, Title, FirstName, LastName, Nationality, IdentityNumber, BirthDate, BirthPlace, PhoneNumber, EmailAdress, HomeAdress, Statut, RegistrationDate) values (&apos;a2f3df33-1f30-4e4f-bc60-f15464775404&apos;, &apos;FA-104-0294&apos;, &apos;2&apos;, &apos;Jason&apos;, &apos;Holmes&apos;, &apos;Poland&apos;, &apos;5316662037634719&apos;, &apos;8/14/2014&apos;, &apos;Jeżów Sudecki&apos;, &apos;9-(542)094-4070&apos;, &apos;jholmes0@springer.com&apos;, &apos;54718 Morning Parkway&apos;, &apos;1&apos;, &apos;6/3/2014&apos;);
        ///insert into Students (StudentGuid, StudentId, Title, FirstName, LastName, Nationality,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Students] ([StudentGuid], [Matricule], [Statut], [Guardian_PersonGuid], [Person_PersonGuid]) VALUES (N&apos;a59feff5-1c3a-4873-9ff0-089b4a6f792e&apos;, N&apos;EX-315-8036&apos;, 0, N&apos;404157e4-4190-454f-9e66-48424f54e056&apos;, N&apos;24dc2b1b-212b-4d05-92c0-bc5c0052c8fa&apos;)
        ///INSERT INTO [dbo].[Students] ([StudentGuid], [Matricule], [Statut], [Guardian_PersonGuid], [Person_PersonGuid]) VALUES (N&apos;9d93f77d-6986-4b52-a4f5-281de28e1ad3&apos;, N&apos;EY-315-8833&apos;, 0, N&apos;f776a990-4de0-4090-baa3-cf2dd5119b77&apos;, N&apos;7833a24a-b9ed-471b-9537-1f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Students_data {
            get {
                return ResourceManager.GetString("Students_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap yes {
            get {
                object obj = ResourceManager.GetObject("yes", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
